language: python
install:
  - pip install -r requirements.txt
# build multiple branches
branches:
  only:
  - develop
  - main
  - travis
before_script:
  - cd ./teamtwo
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - black .
  - flake8 --max-line-length=92
  - coverage run --source='.' manage.py test naturescall
after_success:
  - coveralls
