language: python
before_install:
  - sed '/django-heroku/d' requirements.txt > requirements-build.txt
install:
  - pip install -r requirements-build.txt
# build multiple branches
branches:
  only:
  - develop
  - main
  - travis
before_script:
  - cd ./teamtwo
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - black .
  - flake8 --max-line-length=92
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
