language: python
install:
  - pip install -r requirements.txt
# build multiple branches
branches:
  only:
  - develop
  - main
  - updated_tests
script:
  - black .
  - flake8
  - coverage run --source='.' manage.py test naturescall
after_success:
  - coveralls