# Generated by Django 3.2.9 on 2021-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("naturescall", "0002_claimedrestroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restroom",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
