# Generated by Django 3.2.7 on 2021-11-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="accessible",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="family_friendly",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="transaction_not_required",
            field=models.BooleanField(null=True),
        ),
    ]
